### ISSUE TITLE
HTTPS Checklist

### ISSUE THREAD

**Issue by Ultr4Dev** [Ultr4Dev/rag-code-test-1#9]
- [ ] SSL/TLS certificate
- [ ] Private key
- [ ] Certificate chain
- [ ] Configure server for HTTPS
- [ ] Test HTTPS connection
